
# html lang
language: zh-CN

# header
site_brand_name: 茶馆诗集

logo_image:
  enable: false
  image_path: /images/狗哥看了都说好.png # path to your logo image

menu:
  扉页: /
  诗篇鉴赏: /archives/
  名家一览: /tag/
  # Gallery: /categories/gallery/
  后记: /about/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/menu.js

# favicon
favicon: /images/狗哥看了都说好.ico

date_format: MMM D, YYYY

# profile
profile:
  title: 《茶馆的诗集们！》
  body: 这里是茶馆的大家创作的诗篇集合！万众瞩目的《茶馆的诗集们！》终于发布啦～
  image: /images/狗哥看了都说好.jpg

  links:
    扉页: /
    诗篇鉴赏: /archives/
    名家一览: /tag/
    文集一览（建设中）: /categories/ 
    琴棋书画（建设中）: /categories/gallery/
    后记: /about/

# footer
footer:
  copyright_info:
    enable: true
    author: Made by 白隐Hakuin & 茶馆的大家

  powered_by: # Powered by Hexo & Frame
    enable: true

  other_info:
    enable: true
    content: 感谢大家！！

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: false




# comments: support disqus and valine
valine: # valine setup guide: https://valine.js.org/quickstart.html
  enable: true
  appId: lvSbd25K9zYgC31kSzR65eY2-gzGzoHsz
  appKey: AS5wHlsOHA6cDzSObIJDCVEr
  lang: 'zh-CN'
  placeholder: '请鉴赏家在此留下评价…\n（昵称、邮箱和网址都是非必填的啦）'
  avatar: 'hide'
  enableQQ: true
  meta: ['nick', 'mail', 'link']
  # 设置Bilibili表情包地址
  emojiCDN: '//i0.hdslb.com/bfs/emote/'
  # 表情title和图片映射 
  emojiMaps:
    tv_doge: '6ea59c827c414b4a2955fe79e0f6fd3dcd515e24.png'
    tv_亲亲: a8111ad55953ef5e3be3327ef94eb4a39d535d06.png
    tv_偷笑: bb690d4107620f1c15cff29509db529a73aee261.png
    tv_再见: 180129b8ea851044ce71caf55cc8ce44bd4a4fc8.png
    tv_冷漠: b9cbc755c2b3ee43be07ca13de84e5b699a3f101.png
    tv_发怒: 34ba3cd204d5b05fec70ce08fa9fa0dd612409ff.png
    tv_发财: 34db290afd2963723c6eb3c4560667db7253a21a.png
    tv_可爱: 9e55fd9b500ac4b96613539f1ce2f9499e314ed9.png
    tv_吐血: 09dd16a7aa59b77baa1155d47484409624470c77.png
    tv_呆: fe1179ebaa191569b0d31cecafe7a2cd1c951c9d.png
    tv_呕吐: 9f996894a39e282ccf5e66856af49483f81870f3.png
    tv_困: 241ee304e44c0af029adceb294399391e4737ef2.png
    tv_坏笑: 1f0b87f731a671079842116e0991c91c2c88645a.png
    tv_大佬: 093c1e2c490161aca397afc45573c877cdead616.png
    tv_大哭: 23269aeb35f99daee28dda129676f6e9ea87934f.png
    tv_委屈: d04dba7b5465779e9755d2ab6f0a897b9b33bb77.png
    tv_害羞: a37683fb5642fa3ddfc7f4e5525fd13e42a2bdb1.png
    tv_尴尬: 7cfa62dafc59798a3d3fb262d421eeeff166cfa4.png
    tv_微笑: 70dc5c7b56f93eb61bddba11e28fb1d18fddcd4c.png
    tv_思考: 90cf159733e558137ed20aa04d09964436f618a1.png
    tv_惊吓: 0d15c7e2ee58e935adc6a7193ee042388adc22af.png




disqus: # disqus setup guide: https://help.disqus.com/en/articles/1717056-publisher-quick-start-guide
  enable: false
  disqus_url: # your diqsuq url or shortname
  language: 'cn'



# local search
local_search:
  enable: true
  place_holder: 找找大作…
  trigger: auto # auto: trigger search whenever input changes
  top_n_per_article: 1 # show top n results per article, show all results by setting to -1
  unescape: true # unescape html strings to the readable one
  preload: true # reload the search data when the page loads, this will accelerate the search process
