
# html lang
language: zh-CN

# header
site_brand_name: 茶馆诗集

logo_image:
  enable: false
  image_path: /images/狗哥看了都说好.png # path to your logo image

menu:
  扉页: /
  诗篇鉴赏: /archives/
  名家一览: /tag/
  # Gallery: /categories/gallery/
  后记: /about/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/menu.js

# favicon
favicon: /images/狗哥看了都说好.ico

date_format: MMM D, YYYY

# profile
profile:
  title: 《茶馆的诗集们！》
  body: 这里是茶馆的大家创作的诗篇集合！万众瞩目的《茶馆的诗集们！》终于发布啦～
  image: /images/狗哥看了都说好.jpg

  links:
    扉页: /
    诗篇鉴赏: /archives/
    名家一览: /tag/
    文集一览（建设中）: /categories/ 
    琴棋书画（建设中）: /categories/gallery/
    后记: /about/

# footer
footer:
  copyright_info:
    enable: true
    author: Made by 白隐Hakuin & 茶馆的大家

  powered_by: # Powered by Hexo & Frame
    enable: true

  other_info:
    enable: true
    content: 感谢大家！！

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: false




# comments: support disqus and valine
valine: # valine setup guide: https://valine.js.org/quickstart.html
  enable: true
  appId: lvSbd25K9zYgC31kSzR65eY2-gzGzoHsz
  appKey: AS5wHlsOHA6cDzSObIJDCVEr
  lang: 'zh-CN'
  placeholder: '在此留下鉴赏评价…'
  avatar: 'hide'
  enableQQ: true
  meta: ['nick', 'mail']




disqus: # disqus setup guide: https://help.disqus.com/en/articles/1717056-publisher-quick-start-guide
  enable: false
  disqus_url: # your diqsuq url or shortname
  language: 'cn'



# local search
local_search:
  enable: true
  place_holder: 找找大作…
  trigger: auto # auto: trigger search whenever input changes
  top_n_per_article: 1 # show top n results per article, show all results by setting to -1
  unescape: true # unescape html strings to the readable one
  preload: true # reload the search data when the page loads, this will accelerate the search process
